/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static uas.koneksi.hubungkan;

/**
 *
 * @author Aura Pitaloka
 */
public class mainmenu extends javax.swing.JFrame {

    DefaultTableModel tabelDataPenerbangan;
    DefaultTableModel tabelNormalisasi;
    DefaultTableModel tabelModelNormalisasi;
    DefaultTableModel tabelPerangkingan;

    /**
     * Creates new form mainApp
     */
    public mainmenu() {
        initComponents();
        tampil_data();
        tampil_bobot();
        tampil_alt();
        tabelModelPenerbangan();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_alternatif = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_kode = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_kontak = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_kriteria = new javax.swing.JTextField();
        txt_bobot = new javax.swing.JTextField();
        cmb_label = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        kriteria_label = new javax.swing.JTable();
        btn_bobot_simpan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        txt_fasilitas = new javax.swing.JTextField();
        txt_keamanan = new javax.swing.JTextField();
        txt_kebersihan = new javax.swing.JTextField();
        txt_rating = new javax.swing.JTextField();
        cmb_alt = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        kriteria = new javax.swing.JTable();
        btn_simpan_kriteria = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_penerbangan = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_normalisasi = new javax.swing.JTable();
        btn_normalisasi = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_peringkat = new javax.swing.JTable();
        btn_peringkat = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Selamat Datang ");

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\2.png")); // NOI18N

        jLabel16.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sistem Pendukung Keputusan Pemilihan Maskapai Penerbangan");

        jLabel17.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Metode Simple Additive Weighting (SAW) ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(618, 618, 618)
                        .addComponent(jLabel15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(567, 567, 567)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel17)))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel15)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel16)
                .addGap(34, 34, 34)
                .addComponent(jLabel17)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        tbl_alternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "kode", "name", "kontak"
            }
        ));
        jScrollPane1.setViewportView(tbl_alternatif);

        btn_simpan.setBackground(new java.awt.Color(255, 255, 204));
        btn_simpan.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_simpan.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\sv.png")); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(204, 255, 255));
        btn_batal.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_batal.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-undelete-48.png")); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_hapus.setBackground(new java.awt.Color(204, 255, 204));
        btn_hapus.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_hapus.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-delete-48.png")); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 204, 255));
        btn_edit.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-edit-64.png")); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel5.setText("ID");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setText("Kode Maskapai");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setText("Nama Maskapai");

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setText("Kontak Resmi");

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_kontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kontakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(595, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Alternatif", jPanel4);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel6.setText("kriteria");

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel7.setText("label");

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel8.setText("bobot");

        txt_kriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kriteriaActionPerformed(evt);
            }
        });

        txt_bobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bobotActionPerformed(evt);
            }
        });

        cmb_label.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cost", "benefit" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kriteria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_bobot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_bobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        kriteria_label.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "kriteria", "label", "bobot"
            }
        ));
        jScrollPane2.setViewportView(kriteria_label);

        btn_bobot_simpan.setBackground(new java.awt.Color(255, 255, 204));
        btn_bobot_simpan.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_bobot_simpan.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\sv.png")); // NOI18N
        btn_bobot_simpan.setText("Simpan");
        btn_bobot_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bobot_simpanActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-undelete-48.png")); // NOI18N
        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-delete-48.png")); // NOI18N
        jButton5.setText("Hapus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 255));
        jButton6.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-edit-64.png")); // NOI18N
        jButton6.setText("edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_bobot_simpan)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(587, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bobot_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bobot", jPanel5);

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        jLabel9.setText("Alternatif");

        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel10.setText("Harga");

        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel11.setText("Fasilitas");

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel12.setText("Keamanan");

        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel13.setText("Kebersihan");

        jLabel14.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel14.setText("Rating");

        cmb_alt.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        cmb_alt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garuda Indonesia", "Batik Air", "Lion Air", "Citilink", "Sriwijaya Air" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(108, 108, 108)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_fasilitas)
                            .addComponent(txt_keamanan)
                            .addComponent(txt_kebersihan)
                            .addComponent(txt_rating)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_alt, 0, 242, Short.MAX_VALUE)
                            .addComponent(txt_harga))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_alt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_fasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_keamanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txt_kebersihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_rating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        kriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "alt_id", "harga", "fasilitas", "keamanan", "kebersihan", "rating"
            }
        ));
        jScrollPane3.setViewportView(kriteria);

        btn_simpan_kriteria.setBackground(new java.awt.Color(255, 255, 204));
        btn_simpan_kriteria.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_simpan_kriteria.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\sv.png")); // NOI18N
        btn_simpan_kriteria.setText("Simpan");
        btn_simpan_kriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpan_kriteriaActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-undelete-48.png")); // NOI18N
        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-delete-48.png")); // NOI18N
        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 204, 255));
        jButton4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("D:\\COOLYEAH\\SEMESTER 4\\PEMROGRAMAN KOMPUTER 2\\uas-pemkom2\\src\\img\\icons8-edit-64.png")); // NOI18N
        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btn_simpan_kriteria)
                        .addGap(28, 28, 28)
                        .addComponent(jButton2)
                        .addGap(35, 35, 35)
                        .addComponent(jButton3)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan_kriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );

        jTabbedPane1.addTab("Kriteria", jPanel7);

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        tbl_penerbangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ));
        jScrollPane4.setViewportView(tbl_penerbangan);

        tbl_normalisasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbl_normalisasi);

        btn_normalisasi.setBackground(new java.awt.Color(153, 153, 255));
        btn_normalisasi.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_normalisasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-check-mark-48.png"))); // NOI18N
        btn_normalisasi.setText("NORMALISASI");
        btn_normalisasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalisasiActionPerformed(evt);
            }
        });

        tbl_peringkat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(tbl_peringkat);

        btn_peringkat.setBackground(new java.awt.Color(255, 204, 153));
        btn_peringkat.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btn_peringkat.setText("PERANGKINGAN");
        btn_peringkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_peringkatActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(102, 204, 255));
        jButton7.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jButton7.setText("DATA");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_normalisasi)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 321, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(btn_peringkat)
                        .addGap(629, 629, 629))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(453, 453, 453))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_normalisasi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(btn_peringkat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Proses Data", jPanel9);

        logout.setBackground(new java.awt.Color(255, 153, 153));
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logout))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kontakActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            int row = tbl_alternatif.getSelectedRow(); 
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus terlebih dahulu");
                return;
            }

            int jawaban = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (jawaban == JOptionPane.YES_OPTION) {
                String id = tbl_alternatif.getValueAt(row, 0).toString(); 
                java.sql.Connection conn = koneksi.hubungkan();
                String sql = "DELETE FROM alternatif WHERE `id`=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                tampil_data();
            } else {
                JOptionPane.showMessageDialog(null, "Penghapusan data dibatalkan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal dihapus");
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        txt_kode.setText("");
        txt_name.setText("");
        txt_kontak.setText("");
        tbl_alternatif.requestFocus();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            String sql = "UPDATE tbl_alternatif SET "
                    + "kode='" + txt_kode.getText() + "',"
                    + "name='" + txt_name.getText() + "',"
                    + "kontak='" + txt_kontak.getText() + "' "
                    + "WHERE `id`='" + txt_kode.getText() + "'";

            java.sql.Connection conn = (java.sql.Connection) koneksi.hubungkan();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Perubahan berhasil disimpan");
            tampil_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan perubahan");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // Menyimpan data ke database
        try {
            String sql = "INSERT INTO alternatif (kode, name, kontak) VALUES (?, ?, ?)";
            java.sql.Connection conn = koneksi.hubungkan();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txt_kode.getText());
            pst.setString(2, txt_name.getText());
            pst.setString(3, txt_kontak.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            tampil_data();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void tampil_data() {
        // Menampilkan data dari database ke tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("kode");
        model.addColumn("name");
        model.addColumn("kontak");

        try {
            String sql = "SELECT * FROM alternatif";
            java.sql.Connection conn = koneksi.hubungkan();
            java.sql.Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            tbl_alternatif.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_bobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bobotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bobotActionPerformed

    private void btn_bobot_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bobot_simpanActionPerformed
        try {
            String sql = "INSERT INTO kriteria_label (kriteria, label, bobot) VALUES (?, ?, ?)";
            java.sql.Connection conn = koneksi.hubungkan();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txt_kriteria.getText());
            pst.setString(2, cmb_label.getSelectedItem().toString());
            pst.setString(3, txt_bobot.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            tampil_bobot();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_bobot_simpanActionPerformed

    private void tampil_bobot() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("kriteria");
        model.addColumn("label");
        model.addColumn("bobot");

        try {
            String sql = "SELECT * FROM kriteria_label";
            java.sql.Connection conn = koneksi.hubungkan();
            java.sql.Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4)});
            }
            kriteria_label.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    private void txt_kriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kriteriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kriteriaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cmb_alt.setSelectedItem("");
        txt_harga.setText("");
        txt_fasilitas.setText("");
        txt_keamanan.setText("");
        txt_kebersihan.setText("");
        txt_rating.setText("");
        kriteria.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_simpan_kriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpan_kriteriaActionPerformed
        try {
            String sql = "INSERT INTO kriteria (alt_id, harga, fasilitas, keamanan, kebersihan, rating) VALUES (?, ?, ?, ?, ?, ?)";
            java.sql.Connection conn = koneksi.hubungkan();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, cmb_alt.getSelectedItem().toString());
            pst.setString(2, txt_harga.getText());
            pst.setString(3, txt_fasilitas.getText());
            pst.setString(4, txt_keamanan.getText());
            pst.setString(5, txt_kebersihan.getText());
            pst.setString(6, txt_rating.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

            tampil_alt();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_simpan_kriteriaActionPerformed

    private void btn_normalisasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalisasiActionPerformed
        normalisasi();
    }//GEN-LAST:event_btn_normalisasiActionPerformed

    private void btn_peringkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_peringkatActionPerformed
        tentukanPeringkat();
    }//GEN-LAST:event_btn_peringkatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_kriteria.setText("");
        cmb_label.setSelectedItem("");
        txt_bobot.setText("");
        kriteria_label.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try {
            int row = kriteria_label.getSelectedRow(); 
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus terlebih dahulu");
                return;
            }

            int jawaban = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (jawaban == JOptionPane.YES_OPTION) {
                String id = kriteria_label.getValueAt(row, 0).toString(); 
                java.sql.Connection conn = koneksi.hubungkan();
                String sql = "DELETE FROM kriteria_label WHERE `id`=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                tampil_data();
            } else {
                JOptionPane.showMessageDialog(null, "Penghapusan data dibatalkan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal dihapus");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
        // Siapkan query SQL dengan parameter
        String sql = "UPDATE kriteria_label SET "
                + "kode = ?, "
                + "name = ?, "
                + "kontak = ? "
                + "WHERE id = ?";

        // Buat koneksi ke database
        java.sql.Connection conn = koneksi.hubungkan();
        
        // Buat PreparedStatement dan set parameter
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txt_kriteria.getText());
        pst.setString(2, cmb_label.getSelectedItem().toString());
        pst.setString(3, txt_bobot.getText());
        pst.setString(4, txt_kode.getText());

        // Eksekusi update
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Perubahan berhasil disimpan");

        // Tampilkan data setelah update
        tampil_data();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan perubahan");
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         try {
            int row = kriteria.getSelectedRow(); 
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Pilih baris yang ingin dihapus terlebih dahulu");
                return;
            }

            int jawaban = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin menghapus data?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

            if (jawaban == JOptionPane.YES_OPTION) {
                String id = kriteria.getValueAt(row, 0).toString(); 
                java.sql.Connection conn = koneksi.hubungkan();
                String sql = "DELETE FROM kriteria WHERE `id`=?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                tampil_data();
            } else {
                JOptionPane.showMessageDialog(null, "Penghapusan data dibatalkan");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal dihapus");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      try {
        // Siapkan query SQL dengan parameter
        String sql = "UPDATE kriteria_label SET "
                + "alternatif = ?, "
                + "harga = ?, "
                + "fasilitas = ?, "
                + "keamanan = ?, "
                + "kebersihan = ?, "
                + "rating = ? "
                + "WHERE id = ?";

        // Buat koneksi ke database
        java.sql.Connection conn = koneksi.hubungkan();
        
        // Buat PreparedStatement dan set parameter
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, cmb_alt.getSelectedItem().toString());
        pst.setString(2, txt_harga.getText());
        pst.setString(3, txt_fasilitas.getText());
        pst.setString(4, txt_keamanan.getText());
        pst.setString(5, txt_kebersihan.getText());
        pst.setString(6, txt_rating.getText());
        pst.setString(7, txt_kode.getText());

        // update
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Perubahan berhasil disimpan");

        // Tampilkan data setelah update
        tampil_data();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Gagal menyimpan perubahan: " + e.getMessage());
        System.out.println(e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
       int jawaban = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    if (jawaban == JOptionPane.YES_OPTION) {
        login loginForm = new login(); 
        loginForm.setVisible(true);
        this.dispose(); 
    }
    }//GEN-LAST:event_logoutActionPerformed

    private void tampil_alt() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id");
        model.addColumn("alt_id");
        model.addColumn("harga");
        model.addColumn("fasilitas");
        model.addColumn("keamanan");
        model.addColumn("kebersihan");
        model.addColumn("rating");

        try {
            String sql = "SELECT * FROM kriteria";
            java.sql.Connection conn = koneksi.hubungkan();
            java.sql.Statement stm = conn.createStatement();
            ResultSet res = stm.executeQuery(sql);

            while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7)});
            }
            kriteria.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    public void tabelModelPenerbangan() {
        tabelDataPenerbangan = new DefaultTableModel();
        tabelDataPenerbangan.addColumn("id");
        tabelDataPenerbangan.addColumn("alt");
        tabelDataPenerbangan.addColumn("harga");
        tabelDataPenerbangan.addColumn("fasilitas");
        tabelDataPenerbangan.addColumn("keamanan");
        tabelDataPenerbangan.addColumn("kebersihan");
        tabelDataPenerbangan.addColumn("rating");
        tbl_penerbangan.setModel(tabelDataPenerbangan);

        try {
            ResultSet res = koneksi.ambildata("SELECT * FROM kriteria");
            while (res.next()) {
                tabelDataPenerbangan.addRow(new Object[]{
                    res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5), res.getString(6), res.getString(7)
                });
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    public void tabelModelNormalisasi() {
        tabelNormalisasi = new DefaultTableModel();
        tabelNormalisasi.addColumn("id");
        tabelNormalisasi.addColumn("alt");
        tabelNormalisasi.addColumn("harga");
        tabelNormalisasi.addColumn("fasilitas");
        tabelNormalisasi.addColumn("keamanan");
        tabelNormalisasi.addColumn("kebersihan");
        tabelNormalisasi.addColumn("rating");
        tbl_normalisasi.setModel(tabelNormalisasi);
    }

    public void tabelModelPerangkingan() {
        tabelPerangkingan = new DefaultTableModel();
        tabelPerangkingan.addColumn("id");
        tabelPerangkingan.addColumn("alt");
        tabelPerangkingan.addColumn("nilai");
        tabelPerangkingan.addColumn("peringkat");
        tbl_peringkat.setModel(tabelPerangkingan);
    }

   public void normalisasi() {
    try {
        // Ambil nilai maksimum dan minimum dari database
        ResultSet res = koneksi.ambildata("SELECT MAX(harga) AS maxHarga, "
                + "MIN(harga) AS minHarga, "
                + "MAX(fasilitas) AS maxFasilitas, "
                + "MAX(keamanan) AS maxKeamanan, "
                + "MAX(kebersihan) AS maxKebersihan, "
                + "MAX(rating) AS maxRating "
                + "FROM kriteria");

        float maxHarga = 0, minHarga = 0, maxFasilitas = 0, maxKeamanan = 0, maxKebersihan = 0, maxRating = 0;

        if (res.next()) {
            maxHarga = res.getFloat("maxHarga");
            minHarga = res.getFloat("minHarga");
            maxFasilitas = res.getFloat("maxFasilitas");
            maxKeamanan = res.getFloat("maxKeamanan");
            maxKebersihan = res.getFloat("maxKebersihan");
            maxRating = res.getFloat("maxRating");
        }

        // Bobot dari database
        ResultSet resBobot = koneksi.ambildata("SELECT bobot FROM kriteria_label");
        float bobotHarga = 0, bobotFasilitas = 0, bobotKeamanan = 0, bobotKebersihan = 0, bobotRating = 0;

        if (resBobot.next()) {
            bobotHarga = resBobot.getFloat("bobot");
            if (resBobot.next()) bobotFasilitas = resBobot.getFloat("bobot");
            if (resBobot.next()) bobotKeamanan = resBobot.getFloat("bobot");
            if (resBobot.next()) bobotKebersihan = resBobot.getFloat("bobot");
            if (resBobot.next()) bobotRating = resBobot.getFloat("bobot");
        }

        // Ambil semua data dari database
        ResultSet res2 = koneksi.ambildata("SELECT * FROM kriteria");
        tabelModelNormalisasi();

        while (res2.next()) {
            // Normalisasi harga dengan menggunakan nilai minimum
            float harga = minHarga / res2.getFloat("harga");
            float fasilitas = res2.getFloat("fasilitas") / maxFasilitas;
            float keamanan = res2.getFloat("keamanan") / maxKeamanan;
            float kebersihan = res2.getFloat("kebersihan") / maxKebersihan;
            float rating = res2.getFloat("rating") / maxRating;

            tabelNormalisasi.addRow(new Object[]{
                res2.getString("id"),
                res2.getString("alt"),
                harga,
                fasilitas,
                keamanan,
                kebersihan,
                rating
            });
        }

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
    }
}


public void tentukanPeringkat() {
    try {
        // Ambil bobot dari tabel kriteria_label di database
        String sqlBobot = "SELECT * FROM kriteria_label";
        java.sql.Connection conn = koneksi.hubungkan();
        java.sql.Statement stmBobot = conn.createStatement();
        ResultSet resBobot = stmBobot.executeQuery(sqlBobot);

        // Simpan bobot dari database ke dalam map untuk setiap kriteria
        Map<String, Float> bobotMap = new HashMap<>();
        while (resBobot.next()) {
            String kriteria = resBobot.getString("kriteria");
            float bobot = resBobot.getFloat("bobot");
            bobotMap.put(kriteria, bobot);
        }

        // Inisialisasi tabel perangkingan
        tabelModelPerangkingan();

        List<Float> nilaiList = new ArrayList<>(); // List untuk menyimpan nilai

        // Iterasi setiap baris data pada tabelNormalisasi
        for (int i = 0; i < tabelNormalisasi.getRowCount(); i++) {
            // Ambil nilai dari tabelNormalisasi yang sudah dinormalisasi sebelumnya
            float harga = (float) tabelNormalisasi.getValueAt(i, 2);
            float fasilitas = (float) tabelNormalisasi.getValueAt(i, 3);
            float keamanan = (float) tabelNormalisasi.getValueAt(i, 4);
            float kebersihan = (float) tabelNormalisasi.getValueAt(i, 5);
            float rating = (float) tabelNormalisasi.getValueAt(i, 6);

            // Hitung nilai akhir dengan mengalikan nilai normalisasi dengan bobot dari kriteria_label
            float nilai = (harga * bobotMap.get("harga"))
                    + (fasilitas * bobotMap.get("fasilitas"))
                    + (keamanan * bobotMap.get("keamanan"))
                    + (kebersihan * bobotMap.get("kebersihan"))
                    + (rating * bobotMap.get("rating"));

            nilaiList.add(nilai); // Simpan nilai ke dalam list

            // Tambahkan baris ke tabelPerangkingan dengan id, alternatif, nilai, dan peringkat (masih null)
            tabelPerangkingan.addRow(new Object[]{
                tabelNormalisasi.getValueAt(i, 0), // id
                tabelNormalisasi.getValueAt(i, 1), // alt
                nilai, // nilai
                null // Tempat untuk peringkat, akan diisi kemudian
            });
        }

        // Tentukan peringkat berdasarkan nilai
        float[] nilaiArray = new float[nilaiList.size()];
        for (int i = 0; i < nilaiList.size(); i++) {
            nilaiArray[i] = nilaiList.get(i);
        }

        Arrays.sort(nilaiArray); // Urutkan nilai peringkat

        // Isi nilai peringkat ke dalam tabelPerangkingan
        for (int i = 0; i < tabelPerangkingan.getRowCount(); i++) {
            float nilai = (float) tabelPerangkingan.getValueAt(i, 2);
            // Temukan peringkat dengan mencari posisi nilai dalam nilaiArray
            int peringkat = nilaiList.size() - Arrays.binarySearch(nilaiArray, nilai);
            tabelPerangkingan.setValueAt(peringkat, i, 3); // Set peringkat ke tabel
        }

        // Urutkan tabelPerangkingan berdasarkan kolom peringkat
        DefaultTableModel model = (DefaultTableModel) tbl_peringkat.getModel();
        Vector<Vector> data = model.getDataVector();
        data.sort(Comparator.comparingInt(o -> (int) o.get(3)));

        model.fireTableDataChanged(); // Refresh tabel

        // Hapus kolom id setelah data diurutkan
        tbl_peringkat.removeColumn(tbl_peringkat.getColumnModel().getColumn(0));

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, ex);
    }
}

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_bobot_simpan;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_normalisasi;
    private javax.swing.JButton btn_peringkat;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_simpan_kriteria;
    private javax.swing.JComboBox<String> cmb_alt;
    private javax.swing.JComboBox<String> cmb_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable kriteria;
    private javax.swing.JTable kriteria_label;
    private javax.swing.JButton logout;
    private javax.swing.JTable tbl_alternatif;
    private javax.swing.JTable tbl_normalisasi;
    private javax.swing.JTable tbl_penerbangan;
    private javax.swing.JTable tbl_peringkat;
    private javax.swing.JTextField txt_bobot;
    private javax.swing.JTextField txt_fasilitas;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_keamanan;
    private javax.swing.JTextField txt_kebersihan;
    private javax.swing.JTextField txt_kode;
    private javax.swing.JTextField txt_kontak;
    private javax.swing.JTextField txt_kriteria;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_rating;
    // End of variables declaration//GEN-END:variables

}
